feat/createModuleAddress
context-CODE/hackakenzie_fund-back pull request #10
Opened 2023-11-14 23:38 UTC by C4rt00n3

Foi feito a entidade Address conforme ao DER, as relações com as demais entidades só poderá ser feita após suas criações. Por enquanto ele só se relaciona com a entidade User

2023-11-15 02:18 UTC, vivyribeiro commented on prisma/schema.prisma
> +  address Address?
A relação do Address p/ user é One-to-many, possibilitando o user ter 1 ou varios endereços, então deve definir o campo como: addresses Address[], e ñ precisa tornar o campo opcional.

2023-11-15 02:21 UTC, vivyribeiro commented on prisma/schema.prisma
> +  @@map("address")
Para manter a pradronização das tabelas, use o plural da entidade no @@map.

2023-11-15 02:25 UTC, vivyribeiro requested changes
Rever as mudanças a serem feitas de acordo com as sugestões comentadas no arquivo.

2023-11-15 21:30 UTC, samsks requested changes
Precisa ajustar os erros de linter antes da PR.
Faça o ajuste que o linter solicitar e atualize a branch, para ajustar a PR automaticamente.

2023-11-17 23:50 UTC, closed without merging

2023-11-17 23:50 UTC, samsks commented
Duplicada